name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Build
        run: |
          npm install
          npm run build-sw
          npm run build
          npm test
      - name: Pack
        id: pack
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          ARCHIVE_NAME=audioserve-web-release_${RELEASE_VERSION}.tgz
          echo ::set-output name=ARCHIVE_NAME::$ARCHIVE_NAME
          echo Creating $ARCHIVE_NAME
          tar  czvf $ARCHIVE_NAME -C dist .

      - name: Create release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.pack.outputs.ARCHIVE_NAME }}
